spring:
  application:
    name: financial-transaction-authorization-service

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/db_financial_transactions_authorization}
    username: ${DATABASE_USERNAME:user_financial_transactions_authorization}
    password: ${DATABASE_PASSWORD:password_financial_transactions_authorization}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: false

  docker:
    compose:
      enabled: false

  cloud:
    aws:
      endpoint: ${AWS_ENDPOINT:http://localhost:4566}

      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:test}
        secret-key: ${AWS_SECRET_ACCESS_KEY:test}

      region:
        static: ${AWS_REGION:sa-east-1}

      sqs:
        enabled: true
        observation-enabled: true
        listener:
          max-inflight-messages-per-queue: 10
          max-messages-per-poll: 10
          poll-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${ENVIRONMENT:local}

    distribution:
      percentiles-histogram:
        http.server.requests: true

  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}

    export:
      otlp:
        enabled: true

  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
      deployment.environment.name: ${ENVIRONMENT:local}

    tracing:
      export:
        otlp:
          endpoint: ${OTEL_TRACES_ENDPOINT:http://localhost:4318/v1/traces}

  otlp:
    metrics:
      export:
        enabled: true
        url: ${OTEL_METRICS_ENDPOINT:http://localhost:4318/v1/metrics}
        step: 10s

logging:
  include-application-name: false

  level:
    com.osmarin.financial.transaction.authorization: ${APPLICATION_LOG_LEVEL:INFO}

  pattern:
    correlation: "%replace([${spring.application.name:},%X{traceId:-},%X{spanId:-}]){',+(?=\\])',''} "

application:
  messaging:
    sqs:
      account-created-queue: ${ACCOUNT_CREATED_QUEUE:http://localhost:4566/000000000000/conta-bancaria-criada}
